/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{ts,vue}", "./node_modules/ui-components-3/**/*.mjs"],
  theme: {
    extend: {
      colors: {
        cta: {
          DEFAULT: "var(--color-cta);",
          active: "var(--color-cta-active)",
          contrast: "var(--color-cta-contrast)",
          hover: "var(--color-cta-hover)",
          light: {
            DEFAULT: "var(--color-cta-light)",
            active: "var(--color-cta-light-active)",
            contrast: "var(--color-cta-light-contrast)",
            hover: "var(--color-cta-light-hover)",
          },
        },
        hlt: {
          DEFAULT: "var(--color-hlt)",
          active: "var(--color-hlt-active)",
          contrast: "var(--color-hlt-contrast)",
          hover: "var(--color-hlt-hover)",
          light: {
            DEFAULT: "var(--color-hlt-light)",
            active: "var(--color-hlt-light-active)",
            contrast: "var(--color-hlt-light-contrast)",
            hover: "var(--color-hlt-light-hover)",
          },
        },
        thm: {
          DEFAULT: "var(--color-theme)",
          active: "var(--color-theme-active)",
          contrast: "var(--color-theme-contrast)",
          hover: "var(--color-theme-hover)",
          light: {
            DEFAULT: "var(--color-theme-light)",
            active: "var(--color-theme-light-active)",
            contrast: "var(--color-theme-light-contrast)",
            hover: "var(--color-theme-light-hover)",
          },
        },
        inf: {
          DEFAULT: "var(--color-info)",
          active: "var(--color-info-active)",
          contrast: "var(--color-info-contrast)",
          hover: "var(--color-info-hover)",
          light: "var(--color-info-light)",
          text: "var(--color-info-text)",
        },
        suc: {
          DEFAULT: "var(--color-success)",
          active: "var(--color-success-active)",
          contrast: "var(--color-success-contrast)",
          hover: "var(--color-success-hover)",
          light: "var(--color-success-light)",
          text: "var(--color-success-text)",
        },
        wrn: {
          DEFAULT: "var(--color-warn)",
          active: "var(--color-warn-active)",
          contrast: "var(--color-warn-contrast)",
          hover: "var(--color-warn-hover)",
          light: "var(--color-warn-light)",
          text: "var(--color-warn-text)",
        },
        err: {
          DEFAULT: "var(--color-error)",
          active: "var(--color-error-active)",
          contrast: "var(--color-error-contrast)",
          hover: "var(--color-error-hover)",
          light: "var(--color-error-light)",
          text: "var(--color-error-text)",
        },
        bgr: {
          DEFAULT: "var(--color-bgr)",
          100: "var(--color-bgr100)",
          200: "var(--color-bgr200)",
          300: "var(--color-bgr300)",
          400: "var(--color-bgr400)",
          500: "var(--color-bgr500)",
          600: "var(--color-bgr600)",
          700: "var(--color-bgr700)",
          800: "var(--color-bgr800)",
          900: "var(--color-bgr900)",
        },
        txt: {
          DEFAULT: "var(--color-txt)",
          dim: "var(--color-txt-dim)",
          stress: "var(--color-txt-stress)",
          100: "var(--color-txt100)",
          200: "var(--color-txt200)",
          300: "var(--color-txt300)",
          400: "var(--color-txt400)",
          500: "var(--color-txt500)",
          600: "var(--color-txt600)",
          700: "var(--color-txt700)",
          800: "var(--color-txt800)",
          900: "var(--color-txt900)",
          link: {
            DEFAULT: "var(--color-txt-link)",
            active: "var(--color-txt-link-active)",
            contrast: "var(--color-txt-link-contrast)",
            hover: "var(--color-txt-link-hover)",
          },
        },
        offer: "var(--color-offer)",
        supplier: "var(--color-supplier)",
        accommodation: "var(--color-accommodation)",
      },
    },
  },
  plugins: [],
};
